name: Sayoeti - Kecerdasan Buatan Sebagai Asisten Hubungan Masyarakat KPK
description: Kecerdasan Buatan Sebagai Asisten Humas KPK
meta_description: "Sayoeti adalah keserdasan buatan yang menjadi Asisten Humas KPK"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://sayoeti.xyz'
# google_analytics: 'UA-XXXXXXXX-X'
# disqus: false
# disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://sayoeti.xyz'
author:         'Tim Indonesian AI'
# authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
